apiVersion: apps/v1  
kind: Deployment  
metadata:  
  labels:  
    app: k8s-combat-service # 通过标签选择关联  
  name: k8s-combat-service  
spec:  
  replicas: 2  
  selector:  
    matchLabels:  
      app: k8s-combat-service  
  template:  
    metadata:  
      labels:  
        app: k8s-combat-service  
    spec:  
      containers:  
        - name: k8s-combat-service  
          image: k8s-combat:v1  
          imagePullPolicy: IfNotPresent
          resources:  
            limits:  
              cpu: "1"  
              memory: 100Mi  
            requests:  
              cpu: "0.1"  
              memory: 10Mi  
---  #  分隔符，表示下面是另一个资源定义
apiVersion: v1  
kind: Service  # 服务类型
metadata:  
  name: k8s-combat-service  
spec:  
  selector:  
    app: k8s-combat-service # 通过标签选择关联  
  type: ClusterIP  # 服务类型，ClusterIP 表示只在集群内部可访问，NodePort 表示可以通过节点 IP 和端口访问，LoadBalancer 表示云服务商提供的负载均衡器
  ports:  
    - port: 8081        # 本 Service 的端口  , 如果和容器端口相同，可以省略
      targetPort: 8081  # 容器端口  
      name: app